# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stratified_group_cv_kaggle_interface <- function(strat_vec, group_vec, num_folds) {
    .Call('_mlr3resampling_stratified_group_cv_kaggle_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, num_folds)
}

stratified_group_cv_new_interface <- function(strat_vec, group_vec, num_folds) {
    .Call('_mlr3resampling_stratified_group_cv_new_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, num_folds)
}

