# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stratified_group_cv_Wasikowski_interface <- function(strat_vec, group_vec, num_folds) {
    .Call('_mlr3resampling_stratified_group_cv_Wasikowski_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, num_folds)
}

stratified_group_cv_WasikowskiLimitedMemory_interface <- function(strat_vec, group_vec, num_folds) {
    .Call('_mlr3resampling_stratified_group_cv_WasikowskiLimitedMemory_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, num_folds)
}

stratified_group_cv_RSS_interface <- function(strat_vec, group_vec, num_folds) {
    .Call('_mlr3resampling_stratified_group_cv_RSS_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, num_folds)
}

set_RSS_stats_interface <- function(strat_vec, group_vec, random_order_vec, num_folds, rss_vec, neg_nrow_vec, Wsum_vec, g_ord_vec) {
    invisible(.Call('_mlr3resampling_set_RSS_stats_interface', PACKAGE = 'mlr3resampling', strat_vec, group_vec, random_order_vec, num_folds, rss_vec, neg_nrow_vec, Wsum_vec, g_ord_vec))
}

